//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem2.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBLIBRARY2Entities : DbContext
    {
        public DBLIBRARY2Entities()
            : base("name=DBLIBRARY2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLAUTHOR> TBLAUTHOR { get; set; }
        public virtual DbSet<TBLBOOK> TBLBOOK { get; set; }
        public virtual DbSet<TBLCATEGORY> TBLCATEGORY { get; set; }
        public virtual DbSet<TBLFINESFUND> TBLFINESFUND { get; set; }
        public virtual DbSet<TBLMEMBERS> TBLMEMBERS { get; set; }
        public virtual DbSet<TBLMOVEMENT> TBLMOVEMENT { get; set; }
        public virtual DbSet<TBLPENALTIES> TBLPENALTIES { get; set; }
        public virtual DbSet<TBLSTAFF> TBLSTAFF { get; set; }
        public virtual DbSet<TBLABOUT> TBLABOUT { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLMESSAGES> TBLMESSAGES { get; set; }
        public virtual DbSet<TBLANNOUNCEMENTS> TBLANNOUNCEMENTS { get; set; }
    
        public virtual ObjectResult<string> TheMostBookAuthor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TheMostBookAuthor");
        }
    
        public virtual ObjectResult<string> TheMostReadBook()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TheMostReadBook");
        }
    
        public virtual ObjectResult<string> TopPerformingStaff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TopPerformingStaff");
        }
    
        public virtual ObjectResult<string> TheMostActiveMember()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TheMostActiveMember");
        }
    }
}
