//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLAUTHOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLAUTHOR()
        {
            this.TBLBOOK = new HashSet<TBLBOOK>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="You cannot leave the author name blank")]
        public string NAME { get; set; }
        [StringLength(20,ErrorMessage ="You can enter up to 20 characters")]
        public string SURNAME { get; set; }
        public string DETAILS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBOOK> TBLBOOK { get; set; }
    }
}
