//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBOOK()
        {
            this.TBLMOVEMENT = new HashSet<TBLMOVEMENT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<int> AUTHOR { get; set; }
        public string PUBLICATIONDATE { get; set; }
        public string PUBLISHER { get; set; }
        public string PAGECOUNT { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string BOOKPICTURE { get; set; }
    
        public virtual TBLAUTHOR TBLAUTHOR { get; set; }
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMOVEMENT> TBLMOVEMENT { get; set; }
    }
}
