//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLMEMBERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMEMBERS()
        {
            this.TBLMOVEMENT = new HashSet<TBLMOVEMENT>();
            this.TBLPENALTIES = new HashSet<TBLPENALTIES>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "You cannot leave the name blank")]
        [StringLength(20, ErrorMessage = "You can enter up to 20 characters")]
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string EMAIL { get; set; }
        public string USERNAME { get; set; }
        [StringLength(15, ErrorMessage = "You can enter up to 15 characters")]
        public string PASSWORD { get; set; }
        public string PHOTO { get; set; }
        public string PHONE { get; set; }
        public string SCHOOL { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMOVEMENT> TBLMOVEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPENALTIES> TBLPENALTIES { get; set; }
    }
}
