//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMOVEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMOVEMENT()
        {
            this.TBLPENALTIES = new HashSet<TBLPENALTIES>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BOOK { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<byte> STAFF { get; set; }
        public Nullable<System.DateTime> BORROWDATE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
        public Nullable<bool> TRANSACTIONSTATUS { get; set; }
        public Nullable<System.DateTime> MEMBERRETURNDATE { get; set; }
    
        public virtual TBLBOOK TBLBOOK { get; set; }
        public virtual TBLMEMBERS TBLMEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPENALTIES> TBLPENALTIES { get; set; }
        public virtual TBLSTAFF TBLSTAFF { get; set; }
    }
}
