//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPENALTIES
    {
        public int ID { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<int> MOVEMENT { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> FINISH { get; set; }
        public Nullable<decimal> MONEY { get; set; }
    
        public virtual TBLMEMBERS TBLMEMBERS { get; set; }
        public virtual TBLMOVEMENT TBLMOVEMENT { get; set; }
    }
}
